name: Nightly Snapshot from main
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: 'main'
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    - name: Run Fastlane
      env:
        RELEASE_ENCODED_KEYSTORE: ${{ secrets.RELEASE_ENCODED_KEYSTORE }}
        KEYPASS: ${{ secrets.KEYPASS }}
        STOREPASS: ${{ secrets.STOREPASS }}
        KEYALIAS: ${{ secrets.KEYALIAS }}
        REPOSITORY_NAME: ${{ github.repository }}
        APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec fastlane app_center --env alpha_snapshot
